#!/bin/bash

# Var gets value of first command line argument; the variable value here needs quotes around it or else it won't work
# Syntax below sets default value for the variable if unassigned (i.e. no passed argument)
column="${1:-1}"

# Try #2: This second script does work, as the extra $ and quotes allow awk to see it. 
# Note: NR > 1 means print only the line #s greater than 1 (i.e. don't print the first line).
ls -lh | awk 'NR > 1 {print $'$column'}'